### ISSUE TITLE
Missing file (Duo3DConfig.h)

### ISSUE THREAD

**Issue by wassimrafrafi** [duo3d/duo3d_driver#1]
Hi, 
Thank you for the driver !! but unfortunately I think that there is a missing file :/
duo3d_driver.cpp:36:38: fatal error:
# include <duo3d_driver/Duo3DConfig.h>

Could you fix it please ?

**Comment by duo3d** [comment]
Hi,
We have updated the CMakeLists.txt that now properly generates Duo3DConfig.h file.

**Comment by wassimrafrafi** [comment]
Hi,
I have tried again and unfortunately still unable to find this file :/

**Comment by nvb** [comment]
I am facing this same issue. Building the driver fails with the error:

```
duo3d_driver.cpp:36:38: fatal error: duo3d_driver/Duo3DConfig.h: No such file or directory
```

EDIT: To fix this I needed to run:

```
chmod a+x cfg/Duo3D.cfg
```
